### ISSUE TITLE
Bikeshedding about name

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-promise-allSettled#3]
Should we call this allSettled or something else? What other name ideas have been considered?

**Comment by jasonwilliams** [comment]
`settleAll` would make more sense to me personally.
I've also seen `settle` used in libraries

**Comment by littledan** [comment]
What's a little strange to me about `settle` or `settleAll` is it makes me think that it will modify the Promises that are passed into it (which it won't). (I like `join` as a name for this, but I imagine that'd be confusing given that Bluebird uses the same name for something else.)

**Comment by jasonwilliams** [comment]
@littledan could you explain the reasoning behind .join ? 
I immediately think of the array method and don’t really make the connection here, especially as this would return an array

**Comment by littledan** [comment]
It sounds to me like it would make the promises provided as input become resolved.

**Comment by domenic** [comment]
I think the userland precedent here is pretty compelling for allSettled. I'd also be open to just "settled", under the assumption that being a static method makes it implicit that it will apply to all its arguments.

**Comment by jasonwilliams** [comment]
https://www.npmjs.com/package/rsvp calls the returned object a `state object` should we stick with this convention?

**Comment by ljharb** [comment]
Sounds fine but this seems related to a different issue :-)

**Comment by jasonwilliams** [comment]
Yup @ljharb you're right, i wasn't sure whether it needed a separate thread

**Comment by Ginden** [comment]
Bluebird docs call it `settleAll` BTW.

**Comment by getify** [comment]
Since we're bikeshedding, my 2 cents:

Setting aside userland APIs for a moment, I think it's far more common (and also accurate), both from the perspective of stuff written about JS, and also course materials, to refer to a promise that's either rejected or fulfilled as ***resolved***.

There's already a `Promise.resolve(..)` for creating an already resolved (either fulfilled or rejected) promise. So, going on that precedent, I think we should stick with that terminology, and call the API `Promise.allResolved(..)`.

Other options would be `Promise.every(..)` or `Promise.any(..)`.

> It sounds to me like it would make the promises provided as input become resolved.

I strongly agree with Dan here. Quoting from the very first sentence of the spec here:

"...is to want to settle all promises within an array." That to me reads as strongly suggestive of modifying the states of promises, rather than wait on them to be settled (aka, resolved).

**Comment by ljharb** [comment]
`Promise.resolve` doesn't necessarily generate an already-resolved promise tho - `Promise.resolve(new Promise(() => {}))` will create a forever-pending promise. I think that the terms "resolved" and "fulfilled" are often confused in practice, and it'd be better to avoid that nomenclature.

**Comment by getify** [comment]
> Promise.resolve doesn't necessarily generate an already-resolved promise tho - Promise.resolve(new Promise(() => {}))

OK, fine, but `Promise.allSettled([ new Promise( ()=>{} ) ])` won't ever get a *settled* promise, either, so I think that's just a moot academic point.

> I think that the terms "resolved" and "fulfilled" are often confused in practice, and it'd be better to avoid that nomenclature.

I haven't see much evidence of these terms being confused. Any links to elaborate on that? In my books, I was very careful to spell that out, and I've read many other blogs which similarly stick to those words, and don't seem to be misleading.

I also haven't seen evidence (again, other than userland APIs) for the word "settled" being commonly used to disambiguate in that confusion... any links?

**Comment by ljharb** [comment]
Bluebird uses "settled"; I haven't seen it commonly used otherwise.

I think that the subtleties of "resolved" are lost on many, who often seem to discuss promises as being "resolved or rejected" - when in fact they can be resolved TO rejected, fulfilled, or "pending".

**Comment by leobalter** [comment]
Expressing my preference here for `settled` rather than `allSettled`. To be clear: not a rejection, I celebrate this feature anyway.

I believe this matches just fine with the idioms used for other static methods as `.race` and `.all` and an eventual `.any`. 

Also, I don't see a functional difference between `settled` and `allSettled` enough to not go with the simple option.

**Comment by devsnek** [comment]
`Promise.settled` -> `Promise.raced`?

Whatever we choose, it should be an infinitive.

**Comment by mathiasbynens** [comment]
I fail to see how `raced` describes what this proposal does. Can you elaborate, @devsnek?

**Comment by mathiasbynens** [comment]
Oh, I see what @devsnek is saying. `Promise.settle` sounds good to me.

**Comment by ljharb** [comment]
`settle` to me sounds like it's forcing the promises to be settled, which isn't the case :-/

**Comment by leobalter** [comment]
both settle or settled seems better than allSettled for me.

**Comment by domenic** [comment]
There's two precedents here: adjective `all`, and verb/noun `race`.

`settled` or `allSettled` align with the `all` precedent.

**Comment by getify** [comment]
Another suggestion: `resolveSettled(..)` or `resolveAll(..)`

My thinking is, `resolve(..)` means "create a promise that is (eventually) 'resolve'd to the state of the promise in question."

With `resolveSettled(..)`, it means "create a promise that is (eventually) 'resolve'd to the 'settled' states of all promises."

With `resolveAll(..)`, it means "create a promise that is (eventually) 'resolved' to the settled states of 'all' promises."

**Comment by domenic** [comment]
We're definitely not misusing the term "resolved" for this method.

**Comment by getify** [comment]
For one, you're deliberately making a claim -- that `resolve()` creates confusion or is "misused" -- without any backing for it. And policing this process -- a thread which is supposed to be about opinions -- as if your opinion is somehow more valid than my opinion.

Secondly, my attempts to share opinions are guided from my role as educator. I think that's a valid and necessary voice in the TC39 process. So I don't appreciate a tone that tries to shut out that perspective as invalid.

**Comment by devsnek** [comment]
@getify resolved and settled mean different things and crossing them would be bad news.

**Comment by getify** [comment]
@devsnek I already addressed that concern in (an earlier message of this thread](https://github.com/tc39/proposal-promise-allSettled/issues/3#issuecomment-412647151). From the educator's perspective -- that is, how learners learn and use these features -- I don't think that's a meaningful distinction. Introducing "settled" alongside "resolved" because of the spec-author's perspective probably feels "academically correct" but is, I think, broadly not a good move for how JS is learned and used.

**Comment by mathiasbynens** [comment]
I agree that most developers probably don’t need to know [the difference](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md), @getify. However, when designing a new API, we should stick to the same terminology that’s been used since the standardization of ECMASCript Promises began. This is not a new term.

**Comment by getify** [comment]
@mathiasbynens JS shipped the word `resolve(..)` to mean, ostensibly to most new learners, a "promise that's finished (aka 'settled')". Most example code for promise constructors used `res` or `resolve` for the name of the function callback that does resolution. It's notable that these examples didn't use `full` or `fulfill`. Why? Because that function doesn't just "fulfill", it actually invokes the JS-spec-named "promise resolution" algorithm, as does `Promise.resolve(..)`. Many authors wrote about JS, like myself, and used "resolve" to describe this process of "finishing" a promise (either with fulfillment or rejection")

Given that context, I don't think "settle" has any more established precedent here. Yes, it was used in user-land libs, but that terminology was never exposed by JS itself; "resolve" was.

**Comment by devsnek** [comment]
Whether or not the average user knows or cares about the difference, using colloquial terminology when defining a language is probably not the best direction to take.

**Comment by ljharb** [comment]
What would this hypothetical user think about “resolve” after seeing/understanding `Promise.resolve(Promise.reject())`?

**Comment by getify** [comment]
@ljharb Were I to teach that sort of pattern -- I don't, because I don't think there's any point to it, but... -- I would describe it as "Make a new resolved promise from that rejected promise." Because I've already taught that "resolved" promises can either be fulfilled or rejected, I don't think that would be confusing at all.

**Comment by ljharb** [comment]
And `Promise.resolve(new Promise(() => {}))`?

(I’m going to assume your often-repeated claims that it’s better to teach the warts than to ignore them means you would want to teach both of these patterns)

**Comment by getify** [comment]
> using colloquial terminology when defining a language is probably not the best direction to take.

I'm not talking about what language to use inside the spec, that's definitely not my purview.

I'm talking about opinions on API design aesthetics. Using academically correct names is generally preferable, unless it departs from expected norms for the users, in which case the "colloquial" terminology is preferable in that it captures and communicates what the developer thinks and means, rather than what the spec authors are thinking.

Similar to the ["Priority of Constituencies" principle from the HTML spec](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies), if those two perspectives are ever at odds, the concerns of the end developer should be more paramount than the concerns of the spec author.

**Comment by ljharb** [comment]
When the colloquial term would give a user an incorrect mental model, I’d argue we have a duty to the user to introduce a new term to help clarify it.

**Comment by getify** [comment]
@ljharb `Promise.resolve(new Promise(() => {}))` is even more bizarre than `Promise.resolve(Promise.reject())`. I can't imagine any scenario for either, but I would argue the former is actually harmful and should be avoided at all costs.

Yes, I generally like to teach the warts, but only if they're instructive to folks on what they *should* be doing.

In that sense, I'd only teach `Promise.resolve(new Promise(() => {}))` if my point was to teach them about the dangers of having never-resolved promises, and in particular why they might want to use `Promise.race(..)` with a timeout-promise to avoid forever-hanging.

So to your question, aside from academic JS quizzes for job interviews (which are harmful to the community, btw), were I to show such a dangerous -- dangerous in the sense of actively inviting pit-of-failure design, harder to debug/read/understand code, etc -- piece of code, I would describe it as such:

"Create a promise that will never resolve." I think that's entirely consistent with the mental model I've taught with and have presented thus far in this thread.

> When the colloquial term would give a user an incorrect mental model

Except that I dispute that it's an incorrect mental model. I think it's the most helpful and pragmatic mental model. I haven't heard a single use-case for why distinguishing between "promises that may eventually settle" and "promises that are already resolved" in the API design of JS has any semblance of best practice in teaching.

**Comment by getify** [comment]
Not that my teaching methods are on trial here, but since it's been called into question... to further explain the mental model I use for teaching promises in JS, I teach that promises are intended to normalize value interactions in a time-independent fashion. That is, you shouldn't be thinking or asking "is it finished yet or not", you should be saying, "whenever it's finished, this is what you do next."

As such, distinguishing between a resolved (but not settled) promise and a settled promise are actively counter to that mental model, would be (I think) obstructive to the learning of most developers, and should most definitely not be codified into the API design of the language.

**Comment by hax** [comment]
@getify I agree some may use "resolved" in which they really mean "settled". But unfortunately I see much more use "resolved" in which they really mean "fulfilled", for example jQuery [use "resolved" for "fulfilled" in all APIs/documentation and refuse to fix it](https://bugs.jquery.com/ticket/11395). 

It's not only jQuery. I talked to some educators in Chinese JS community to investigate this problem, and we have consensus that many understand "resolved" as "fulfilled" because of:

1. The APIs are `Promise.resolve` vs `Promise.reject`, and `new Promise((resolve, reject) => ...)`, so it's very easy to treat resolved/rejected as a duality instead of fulfilled/rejected (yes there is `promise.then(onFulfilled, onRejected)`, but in most cases, programmers only use `promise.then(callback)`)
1. Both `resolved` and `rejected` start with `re` prefix and both are 8 letters, so as intuition/aesthetic, programmers paired resolved/rejected instead of fulfilled/rejected 😂
1. It seems in most cases programmers just `resolve` to a normal value so you can use `fulfill` interchangeably, and rarely `resolve` to another promise/thenable

To be wise after the event, we may reform the promise APIs to `Promise.fulfill(value)` (throw TypeError if `value` is promise/thenable), `Promise.delegate(thenable)` and `Promise.reject(reason)` which can solve "resolved" confusions. But it's too late...

Anyway, I think it's not a good idea to use `resolve` in this API to add new chaos to unresolvable `resolved` issue 😝

---

On the other hand, I agree "settle" is not a well-known word, for example, original Promise A+ spec never use "settle". And some libraries like jQuery (jQuery again! 🤪) [never use word "settle"](https://www.google.com/search?q=settle+site%3Aapi.jquery.com) too.

So here are alternavites I can imagine:

- `Promise.finally()`, `Promise.finallyAll` (if this, I'd expect `Promise.prototype.finally` to be upgraded to also receive `{status, value}` object from the callback)
- `Promise.finished()`, `Promise.allFinished()` (it seems "finish" is a much colloquial word than "settle" and hopefully do not have confusion like "resolve")
- `Promise.complete()`, `Promise.completed()`, `Promise.allComplete()`, `Promise.allCompleted()` ("complete" from old jQuery API)
- `Promise.fulfilledOrRejected()`, `Promise.allFulfilledOrRejected()`  (wordy, but at least easy to understand and match the spec terminology 🤓)

**Comment by getify** [comment]
> Anyway, I think it's not a good idea to use resolve in this API to add new chaos to unresolvable resolved issue

What you call chaos, an educator calls consistency. The points you make IMO are far more in favor of my position than against it.

Whether it's right or wrong, if people have come to believe a word means (or is related to) something, the best thing to do is not try to "outsmart" them by correcting (only) new APIs to a more accurate term, while leaving existing ones untouched -- inconsistency breeds confusion in learners. Rather, you gently pave the cowpaths and fix up whatever you can behind the scenes to keep them from tripping.

**Comment by hax** [comment]
@Mouvedia `something all break` seems not a good name 🤪

`Promise.all(array, { settle: true })` doesn't solve the problem because the problem (unfamiliar term "settle") still there, and how we interpret `Promise.all(array, { settle: false })`?

**Comment by Mouvedia** [comment]
@hax the idea is the second parameter, the name of the boolean property is up to you all. The default could be `true` or `false` depending on the name chosen.

**Comment by hax** [comment]
@Mouvedia Overload one method for some different usage may be not a good thing. Note the shape of the return array in `Promise.all` and `Promise.allSettled` are different.

**Comment by Mouvedia** [comment]
> Note the shape of the return array in Promise.all and Promise.allSettled are different.

In what way?

**Comment by Mouvedia** [comment]
If we did pick the option object we would have to normalize the returned array somehow. It's not practical though so that proposal (second argument) is not retained.

**Comment by Mouvedia** [comment]
> `something all break` seems not a good name

@hax well I don't wanna introduce `Promise.all.<foo>()` without its pendant. `Promise.all` must be retroactively made the shorthand. I wanted to reuse keywords that were familiar to JS developers and made sense: `break` or `continue` on rejection.

**Comment by hax** [comment]
@Mouvedia At least I don't get it directly why it's `break` or `continue`... Only after second thought, I realize you mean what happen when rejected. But I think most programmers won't consider negative path first.

To me, the most simple word is `allFinished`, see the last paragraph of my previous comment: https://github.com/tc39/proposal-promise-allSettled/issues/3#issuecomment-428513134

**Comment by Sxderp** [comment]
I've never read the Promise spec directly. My knowledge comes from reading terse documentation and looking at code examples. And @hax has a point, 'in the wild' people use the term "resolved" to indicate "a promise that has been fulfilled". Actually, I'd never even seen the term "fulfilled" in relation to promises until I stumbled on this issue!

As stated before, I believe the confusion is compounded by the fact that by convention people use `new Promise((resolve, reject) => {});` and the API calls are `Promise.resolve` and `Promise.reject` which seem to correlate (at first glance/high level) to the same "fulfilled"[1] and "rejected" callbacks. I've always treated the two API calls as methods to instantly create new "fulfilled"[1] or "rejected" promises. 

If we take the API call `Promise.resolve(thenable)`, again something I didn't know was even valid until this issue, then it makes sense why `"resolved" != "fulfilled"`. As `Promise.resolve(Promise.reject('foo'))` returns a rejected promise. If the API call was named `Promise.fulfill` and didn't allow thenables then perhaps there would be less misused terminology, I dunno.

With my new knowledge, I think this stems from poor choice of keywords in the initial spec. Of course, it's difficult to predict how words are going to be used in the future; even in every day language definitions change, words are lost, and new ones are created. My point is, there's no way to stop people from using the incorrect terms. It's a losing battle to try and fight that.

Adding a method `Promise.resolveAll` with, what I feel is commonly diffused terminology, sounds as if the function is either going to "make all of these promises fulfilled" or have the same functionality as `Promise.all`. On the other hand, when I saw `Promise.allSettled` I felt like I almost immediately new the purpose and could correlate it's actions with it's name. `Promise.settleAll` also works, but I'm not sure about `Promise.settle` as it doesn't quite convey that it takes an array. In reality it sounds like what `Promise.resolve(thenable)` should have been (in which the function is split into two functions, one that takes a thenable which flattens it and another that creates a fulfilled promise).

[1] Where in my head I have (had?) the assumption "resolved" = "fulfilled".

**Comment by mathiasbynens** [comment]
We've briefly discussed the naming issue at the September 2018 TC39 meeting (I had a slide about it), and there was consensus on using `settle` in the name. I'll mention this again at this month's TC39 meeting and will attempt to get this consensus explicitly recorded in the meeting notes.

Given that "settled" is the only [correct term](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md) for a promises that is not pending (i.e. what this proposal is about), and that the name `allSettled` in particular has [strong precedent in userland libraries](https://github.com/tc39/proposal-promise-allSettled#userland-implementations), I'm proposing we stick with `allSettled`. It doesn't make sense to use an incorrect term, or to invent a new term for the same thing.

**Comment by getify** [comment]
> Being settled is not a state, just a linguistic convenience.

But by all means, let's design APIs as if it's an indisputed scientifically precise term!

**Comment by Mouvedia** [comment]
```
Promise.all
Promise.race
Promise.reject
Promise.resolve
Promise#catch
Promise#finally
Promise#then
```

The current API is clean. Could we be consistent and keep the one word convention?

e.g.
```js
/*
  Promise.every(iterable, ?options = {
    fulfilled: true,
    rejected: true
  })
*/

// default behaviour
const promises = [ fetch('index.html'), fetch('https://does-not-exist/') ];
const results = await Promise.every(promises);
const successfulPromises = results.filter(p => p.status === 'fulfilled');

// all must be rejected (doesn't have an equivalent in the current proposal)
Promise.every(promises, { fulfilled: false })
  .then(everyPromiseFailed, atLeastOneWasFulfilled)

// all must be fulfilled (equivalent of Promise.all)
Promise.every(promises, { rejected: false })
  .then(everyPromiseFulfilled, atLeastOneWasRejected)
```

**Comment by SMotaal** [comment]
Some ideas that come to mind without strong opinions of my own: `Promise.once([… /* immediately resolve once those promises settle and … */])` and `Promise.when([… /* when those promises are settled do … */])` — Intuition (my own) may associate `when` with customElements.when, and `once` with one-time listeners, so `once` feels more immediate, `when` somewhat more passive in comparison, but far less passive than `Promise.all(…).finally(…)` (imho).

I guess the important thing to mention is naming this operation will likely see less confusion or distortions if its operant is qualified as the `Promise.all([…]) => promise` instance (more intuitive imho) compared to when considering naming a member that hangs of the `Promise` constructor just because it does and probably should by all means. I may be absolutely completely wrong about all this, thoughts?

**Comment by mathiasbynens** [comment]
Thanks for the feedback, everyone!

Per consensus in today’s TC39 meeting, we’re moving forward with the name `allSettled`.

**Comment by IDisposable** [comment]
late to the shed, but would have suggested `allFates` since we're really looking for the [states and fates](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md)

**Comment by mathiasbynens** [comment]
@IDisposable No, we’re looking for 2 out of the 3 _states_, per the document you pointed to.

**Comment by Mouvedia** [comment]
IMHO `Promise.every(Iterable, predicate = status => bool)` would have been a much better choice.

I wish this was less privy to the TC39 and that this kind of issue had been presented to a much larger panel of users.

**Comment by samson-sham** [comment]
`Promise.every()` would be confusing with `Promise.all()`, I'm sure this would not be a problem to experienced programmer, but to newbie, it would be a headache. An explicit name would be good enough. I'm good with `.allSettled()`
